export const tipoidentificacion = [{valor: 'C.C.', nombre: 'Cédula de Ciudadanía'}, {valor: 'N.I.T.', nombre: 'Número de identificación tributaria'}];

export const tipoimpuesto = [{valor: 'ICA', nombre: 'ICA'},
          {valor: 'PREDIAL', nombre: 'PREDIAL'}, {valor: 'VEHICULOS', nombre: 'VEHÍCULOS'},
          {valor: 'DELINEACIÓN URBANA', nombre: 'DELINEACIÓN URBANA'}, {valor: 'NINGUNO', nombre: 'NINGUNO'}];

export const causaldevolucion = [{valor: 'CERRADO', nombre: 'CERRADO'},
  {valor: 'FALLECIDO', nombre: 'FALLECIDO'}, {valor: 'NO RESIDE', nombre: 'NO RESIDE'}, {valor: 'REHUSADO', nombre: 'REHUSADO'},
  {valor: 'DESCONOCIDO', nombre: 'DESCONOCIDO'}, {valor: 'DIRECCION ERRADA', nombre: 'DIRECCIÓN ERRADA'},
  {valor: 'DIRECCION NO EXISTE', nombre: 'DIRECCIÓN NO EXISTE'}];

export const tiporecurso = [{valor: 'RECONSIDERACION', nombre: 'RECONSIDERACIÓN'},
  {valor: 'REPOSICION', nombre: 'REPOSICIÓN'}, {valor: 'APELACION', nombre: 'APELACIÓN'}];

export const tipopublicacion = [{valor: 'REGISTRO DISTRITAL', nombre: 'REGISTRO DISTRITAL'},
  {valor: 'DIARIO DE AMPLIA CIRCULACION', nombre: 'DIARIO DE AMPLIA CIRCULACIÓN'}];

export const tiporecursopreced = [{valor: 'RECONSIDERACION', nombre: 'RECONSIDERACIÓN'},
  {valor: 'EXCEPCIONES', nombre: 'EXCEPCIONES'}, {valor: 'N/A', nombre: 'N/A'},
  {valor: 'NO PROCEDE', nombre: 'NO PROCEDE'},
  {valor: 'RECONSIDERACION', nombre: 'RECONSIDERACIÓN'},
  {valor: 'REPOSICION', nombre: 'REPOSICIÓN'},
  {valor: 'REPOSICION Y APELACION', nombre: 'REPOSICIÓN Y APELACIÓN'},];

export const tipoacto = [{valor: 'AUTO ACLARATORIO', nombre: 'AUTO ACLARATORIO'},
  {valor: 'AUTO DE ARCHIVO', nombre: 'AUTO DE ARCHIVO'},
  {valor: 'AUTO DE DESISTIMIENTO', nombre: 'AUTO DE DESISTIMIENTO'},
  {valor: 'AUTO DE INSPECCION', nombre: 'AUTO DE INSPECCIÓN'},
  {valor: 'AUTO DE INSPECCION TRIBUTARIA', nombre: 'AUTO DE INSPECCIÓN TRIBUTARIA'},
  {valor: 'AUTO DE VERIFICACION O CRUCE', nombre: 'AUTO DE VERIFICACIÓN O CRUCE'},
  {valor: 'AUTO DECLARATIVO', nombre: 'AUTO DECLARATIVO'},
  {valor: 'AUTO INADMISORIO', nombre: 'AUTO INADMISORIO'},
  {valor: 'AUTO INADMISORIO DE SOLICITUD DE DEVOLUCION Y/O COMPENSACION', nombre: 'AUTO INADMISORIO DE SOLICITUD DE DEVOLUCION Y/O COMPENSACION'},
  {valor: 'AUTO INCLUSORIO / EXCLUSORIO', nombre: 'AUTO INCLUSORIO / EXCLUSORIO'},
  {valor: 'AUTO INSPECCION TRIBUTARIA', nombre: 'AUTO INSPECCIÓN TRIBUTARIA'},
  {valor: 'AUTO QUE ADMITE UN RECURSO DE RECONSIDERACION', nombre: 'AUTO QUE ADMITE UN RECURSO DE RECONSIDERACIÓN'},
  {valor: 'AUTO QUE CONFIRMA AUTO INADMISORIO', nombre: 'AUTO ACLARATORIO'},
  {valor: 'AUTO QUE CONFIRMA EL AUTO INADMISORIO O QUE ADMITE EL RECURSO', nombre: 'AUTO QUE CONFIRMA EL AUTO INADMISORIO O QUE ADMITE EL RECURSO'},
  {valor: 'EMPLAZAMIENTO PARA CORREGIR', nombre: 'EMPLAZAMIENTO PARA CORREGIR'},
  {valor: 'EMPLAZAMIENTO PARA DECLARAR', nombre: 'EMPLAZAMIENTO PARA DECLARAR'},
  {valor: 'LIQUIDACION DE AFORO', nombre: 'LIQUIDACIÓN DE AFORO'},
  {valor: 'LIQUIDACIÓN DE CORRECCION SANCION', nombre: 'LIQUIDACIÓN DE CORRECCIÓN SANCIÓN'},
  {valor: 'LIQUIDACION OFICIAL DE AFORO', nombre: 'LIQUIDACION OFICIAL DE AFORO'},
  {valor: 'LIQUIDACION OFICIAL DE CORRECCION POR MENOR VALOR', nombre: 'LIQUIDACIÓN OFICIAL DE CORRECCIÓN POR MENOR VALOR'},
  {valor: 'LIQUIDACION OFICIAL DE CORRECCIÓN SANCIÓN', nombre: 'LIQUIDACIÓN OFICIAL DE CORRECCIÓN SANCIÓN'},
  {valor: 'LIQUIDACION OFICIAL DE REVISION', nombre: 'LIQUIDACIÓN OFICIAL DE REVISIÓN'},
  {valor: 'LIQUIDACION PROVISIONAL', nombre: 'LIQUIDACIÓN PROVISIONAL'},
  {valor: 'MANDAMIENTO DE PAGO', nombre: 'MANDAMIENTO DE PAGO'},
  {valor: 'MODIFICACION MANDAMIENTO DE PAGO', nombre: 'MODIFICACIÓN MANDAMIENTO DE PAGO'},
  {valor: 'PLIEGO DE CARGOS', nombre: 'PLIEGO DE CARGOS'},
  {valor: 'PLIEGO DE CARGOS POR NO REMITIR INFORMACIÓN', nombre: 'PLIEGO DE CARGOS POR NO REMITIR INFORMACIÓN'},
  {valor: 'PLIEGO DE CARGOS POR SANCION MAL LIQUIDADA', nombre: 'PLIEGO DE CARGOS POR SANCIÓN MAL LIQUIDADA'},
  {valor: 'REQUERIMIENTO DE INFORMACIÓN', nombre: 'REQUERIMIENTO DE INFORMACIÓN'},
  {valor: 'REQUERIMIENTO ESPECIAL', nombre: 'REQUERIMIENTO ESPECIAL'},
  {valor: 'RESOLUCION  TERMINACION  PROCESO', nombre: 'RESOLUCIÓN TERMINACIÓN PROCESO'},
  {valor: 'RESOLUCIÓN DE DEVOLUCIÓN Y/O COMPENSACIÓN', nombre: 'RESOLUCIÓN DE DEVOLUCIÓN Y/O COMPENSACIÓN'},
  {valor: 'RESOLUCION DE FACILIDAD DE PAGO', nombre: 'RESOLUCIÓN DE FACILIDAD DE PAGO'},
  {valor: 'RESOLUCION DE INCUMPLIMIENTO DE UNA FACILIDAD DE PAGO', nombre: 'RESOLUCIÓN DE INCUMPLIMIENTO DE UNA FACILIDAD DE PAGO'},
  {valor: 'RESOLUCION DE PRESCRIPCION', nombre: 'RESOLUCION DE PRESCRIPCIÓN'},
  {valor: 'RESOLUCION DE PRESCRIPCION A SOLICITUD DE PARTE', nombre: 'RESOLUCIÓN DE PRESCRIPCIÓN A SOLICITUD DE PARTE'},
  {valor: 'RESOLUCIÓN DE REDUCCION SANCION', nombre: 'RESOLUCIÓN DE REDUCCIÓN SANCIÓN'},
  {valor: 'RESOLUCIÓON DE TERMINACION DE PROCESO', nombre: 'RESOLUCIÓN DE TERMINACIÓN DE PROCESO'},
  {valor: 'RESOLUCION FACILIDAD DE PAGO', nombre: 'RESOLUCIÓN FACILIDAD DE PAGO'},
  {valor: 'RESOLUCION QUE FALLA EXCEPCIONES', nombre: 'RESOLUCIÓN QUE FALLA EXCEPCIONES'},
  {valor: 'RESOLUCION QUE INADMITE EXCEPCIONES', nombre: 'RESOLUCIÓN QUE INADMITE EXCEPCIONES'},
  {valor: 'RESOLUCION QUE ORDENA SEGUIR ADELANTE CON EL PROCESO', nombre: 'RESOLUCIÓN QUE ORDENA SEGUIR ADELANTE CON EL PROCESO'},
  {valor: 'RESOLUCION QUE ORDENA SEGUIR ADELANTE LA EJECUCION ', nombre: 'RESOLUCION QUE ORDENA SEGUIR ADELANTE LA EJECUCION '},
  {valor: 'RESOLUCIÓN QUE ORDENA SEGUIR ADELANTE LA EJECUCION CONTRA EL RESPONSABLE DEL PAGO DE LAS DEUDAS', nombre: 'RESOLUCIÓN QUE ORDENA SEGUIR ADELANTE LA EJECUCIÓN CONTRA EL RESPONSABLE DEL PAGO DE LAS DEUDAS'},
  {valor: 'RESOLUCIÓN QUE ORDENA SEGUIR CON LA EJECUCIÓN', nombre: 'RESOLUCIÓN QUE ORDENA SEGUIR CON LA EJECUCIÓN'},
  {valor: 'RESOLUCION QUE RESUELVE NULIDAD', nombre: 'RESOLUCIÓN QUE RESUELVE NULIDAD'},
  {valor: 'RESOLUCION REDUCCION SANCION', nombre: 'RESOLUCIÓN REDUCCION SANCIÓN'},
  {valor: 'RESOLUCION SANCION', nombre: 'RESOLUCIÓN SANCIÓN'},
  {valor: 'RESOLUCION TERMINACION DE PROCESO', nombre: 'RESOLUCIÓN TERMINACIÓN DE PROCESO'},
  {valor: 'REVOCATORIA', nombre: 'REVOCATORIA'},
  {valor: 'REVOCATORIA DE OFICIO', nombre: 'REVOCATORIA DE OFICIO'},
  {valor: 'REVOCATORIA DIRECTA', nombre: 'REVOCATORIA DIRECTA'},
  {valor: 'REVOCATORIA DIRECTA Y/O DE OFICIO', nombre: 'REVOCATORIA DIRECTA Y/O DE OFICIO'},
  {valor: 'SANCION POR NO DECLARAR', nombre: 'SANCIÓN POR NO DECLARAR'},
  {valor: 'SOLICITUD REDUCCION SANCIÓN', nombre: 'SOLICITUD REDUCCION SANCIÓN'},
  {valor: 'TERMINACION DE PROCESO DE COBRO COACTIVO', nombre: 'TERMINACIÓN DE PROCESO DE COBRO COACTIVO'}



];
